# Generated by Django 4.1.7 on 2023-04-07 06:06

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64)),
                ('slug', models.CharField(default='', max_length=96)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
                ('subtitle', models.CharField(default='', max_length=256)),
                ('description', models.CharField(default='', max_length=512)),
                ('body', ckeditor.fields.RichTextField(default='')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('is_pin', models.BooleanField(default=False, verbose_name='Is Pin')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Publised')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('tags', models.ManyToManyField(blank=True, to='blogcore.tag')),
            ],
        ),
    ]
