# Generated by Django 4.1.7 on 2023-04-07 06:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
                ('subtitle', models.CharField(default='', max_length=256)),
                ('about', ckeditor.fields.RichTextField(default='')),
            ],
        ),
    ]
